export { MotifPanel } from "./components/MotifPanel"
export { TransformPanel } from "./components/TransformPanel"
export { CanvasWorkspace } from "./components/CanvasWorkspace"
export { TargetPanel } from "./components/TargetPanel"
export { BottomBar } from "./components/BottomBar"
export type { Motif, HistoryEntry, Coord } from "./types"
export { motifs, mockHistory, canvasMotifSrc, targetMotifSrc } from "./data"
